### ISSUE TITLE
Compatibility with Gnome Shell v3.32

### ISSUE THREAD

**Issue by KopfKrieg** [jaystrictor/gnome-shell-extension-syncthing#44]
Currently the extension is not officially compatible with Gnome Shell v3.32. Could you make it compatible? Unfortunately right now I can't provide more infos, but a simple version adjustment probably isn't enough:

```
$ journalctl -b /usr/bin/gnome-shell | grep syncthingicon
Mär 15 23:25:42 Gwynbleidd gnome-shell[1271]: Extension "syncthingicon@jay.strict@posteo.de" had error: TypeError: this._construct is not a function
Mär 15 23:30:53 Gwynbleidd gnome-shell[1271]: Extension "syncthingicon@jay.strict@posteo.de" had error: TypeError: _syncthing is undefined
Mär 15 23:30:53 Gwynbleidd gnome-shell[1271]: Extension "syncthingicon@jay.strict@posteo.de" had error: TypeError: this._construct is not a function
Mär 15 23:32:33 Gwynbleidd gnome-shell[3597]: Extension "syncthingicon@jay.strict@posteo.de" had error: TypeError: this._construct is not a function
$
```

**Comment by coxackie** [comment]
Can confirm that master does not work with Gnome 3.32.

**Comment by jaystrictor** [comment]
Thank you for the report. I will look into it.

**Comment by jaystrictor** [comment]
I have ported the extension to the new ES6 style javascript classes, and there are no errors any more.

However... the icon is not displayed in the top bar. Although the area is clickable and the menu just opens fine. I am not sure what to make of this. Currently, I think this is a bug for how icon name lookup is handled by gnome-shell / Gio / Gtk / St.

**Comment by coxackie** [comment]
Thanks @jaystrictor - for the icon issue, maybe this can help:
https://github.com/neffo/bing-wallpaper-gnome-extension/pull/49

**Comment by jaystrictor** [comment]
Thanks for the hint. I am tracking this in a distinct issue (#45).
